#!/bin/bash
#
# Search for GPG keys on pgp.mit.edu.
# Despite the name, search keys don't have to be email addresses; you can also search by name and comment.
# Uses an exact match search.
#
# stdin: search queries, one per line
# stdout: the search results, if any, in HTML format
# stderr: a message for each search that yields no results
#
# Example, with email_list.txt containing email addresses, one per line:
#   gpg-email-search < email_list.txt | tee results.html
echo '<!DOCTYPE html>'
echo '<html><body><pre>'
while read email; do
  if ! curl -s "http://pgp.mit.edu:11371/pks/lookup?op=index&exact=on&search=$email" | grep '<pre>' -A1 | grep -v '<pre>'; then
    echo "Not found: $email" >&2
  fi | sed -e 's#href="#href="http://pgp.mit.edu:11371#g'
done
echo '</pre></body></html>'
